// <auto-generated />
using AppPenilaianSiswaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppPenilaianSiswaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Guru", b =>
                {
                    b.Property<int>("GuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuruId"));

                    b.Property<string>("GuruName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GuruId");

                    b.ToTable("Gurus");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Jurusan", b =>
                {
                    b.Property<int>("JurusanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JurusanId"));

                    b.Property<string>("NamaJurusan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("JurusanId");

                    b.ToTable("Jurusans");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Kelas", b =>
                {
                    b.Property<int>("KelasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KelasId"));

                    b.Property<int>("JurusanId")
                        .HasColumnType("int");

                    b.Property<string>("NamaKelas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KelasId");

                    b.HasIndex("JurusanId");

                    b.ToTable("Kelas");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Mapel", b =>
                {
                    b.Property<int>("MapelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapelId"));

                    b.Property<int>("GuruId")
                        .HasColumnType("int");

                    b.Property<string>("NamaMapel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MapelId");

                    b.HasIndex("GuruId");

                    b.ToTable("Mapels");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Nilai", b =>
                {
                    b.Property<int>("NilaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NilaiId"));

                    b.Property<int>("MapelId")
                        .HasColumnType("int");

                    b.Property<int>("NilaiSiswa")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("SiswaId")
                        .HasColumnType("int");

                    b.HasKey("NilaiId");

                    b.HasIndex("MapelId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("SiswaId");

                    b.ToTable("Nilais");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperatorId"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OperatorId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Siswa", b =>
                {
                    b.Property<int>("SiswaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiswaId"));

                    b.Property<int>("KelasId")
                        .HasColumnType("int");

                    b.Property<string>("NamaSiswa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nisn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SiswaPicture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SiswaId");

                    b.HasIndex("KelasId");

                    b.ToTable("Siswas");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Kelas", b =>
                {
                    b.HasOne("AppPenilaianSiswaAPI.Models.Jurusan", "Jurusan")
                        .WithMany("Kelas")
                        .HasForeignKey("JurusanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jurusan");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Mapel", b =>
                {
                    b.HasOne("AppPenilaianSiswaAPI.Models.Guru", "Guru")
                        .WithMany("Mapels")
                        .HasForeignKey("GuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guru");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Nilai", b =>
                {
                    b.HasOne("AppPenilaianSiswaAPI.Models.Mapel", "Mapel")
                        .WithMany("Nilais")
                        .HasForeignKey("MapelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppPenilaianSiswaAPI.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppPenilaianSiswaAPI.Models.Siswa", "Siswa")
                        .WithMany("Nilais")
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapel");

                    b.Navigation("Operator");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Operator", b =>
                {
                    b.HasOne("AppPenilaianSiswaAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Siswa", b =>
                {
                    b.HasOne("AppPenilaianSiswaAPI.Models.Kelas", "Kelas")
                        .WithMany()
                        .HasForeignKey("KelasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelas");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Guru", b =>
                {
                    b.Navigation("Mapels");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Jurusan", b =>
                {
                    b.Navigation("Kelas");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Mapel", b =>
                {
                    b.Navigation("Nilais");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AppPenilaianSiswaAPI.Models.Siswa", b =>
                {
                    b.Navigation("Nilais");
                });
#pragma warning restore 612, 618
        }
    }
}
